# Generated by Django 4.1.4 on 2023-05-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServDeskBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=230, verbose_name='Ключ')),
                ('value', models.TextField(max_length=500, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'настройка Service Desk Bot',
                'verbose_name_plural': 'настройки Service Desk Bot',
                'ordering': ['-id'],
            },
        ),
    ]
