# Generated by Django 4.1.4 on 2022-12-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_bot', '0002_alter_bankdata_bik_alter_bankdata_cor_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusers',
            name='tlg_id',
            field=models.CharField(max_length=20, verbose_name='Telegram ID'),
        ),
    ]
