# Generated by Django 4.1.4 on 2022-12-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_bot', '0003_alter_botusers_tlg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusers',
            name='tlg_id',
            field=models.IntegerField(default=0, verbose_name='Telegram ID'),
        ),
    ]
