# Generated by Django 4.1.4 on 2022-12-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_bot', '0004_alter_botusers_tlg_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdata',
            name='cor_a',
            field=models.CharField(max_length=20, verbose_name='Кор.счёт'),
        ),
        migrations.AlterField(
            model_name='bankdata',
            name='rs',
            field=models.CharField(max_length=20, verbose_name='Расч.счёт'),
        ),
        migrations.AlterField(
            model_name='botusers',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Контактный email'),
        ),
    ]
