# Generated by Django 4.1.4 on 2023-01-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_bot', '0005_alter_bankdata_cor_a_alter_bankdata_rs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botusers',
            name='open_line_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID откр.линии'),
        ),
    ]
