# Generated by Django 4.1.4 on 2023-01-11 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_bot', '0006_botusers_open_line_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='top_management_name',
            field=models.CharField(blank=True, max_length=85, null=True, verbose_name='ФИО управляющего'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='top_management_post',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность управляющего комп.'),
        ),
    ]
