# Generated by Django 4.1.4 on 2023-01-14 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_bot', '0007_alter_companydata_top_management_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botusers',
            name='open_line_id',
        ),
        migrations.AddField(
            model_name='botusers',
            name='chat_for_deal_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID чата для сделки'),
        ),
    ]
