# Generated by Django 4.1.4 on 2023-01-16 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_bot', '0008_remove_botusers_open_line_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='botusers',
            name='consent_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время согласия на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='botusers',
            name='consent_to_pers_data',
            field=models.BooleanField(default=False, verbose_name='Согласие на обработку персональных данных'),
        ),
        migrations.AddField(
            model_name='companydata',
            name='requisite_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID реквизита в Битриксе'),
        ),
    ]
