# Generated by Django 4.1.4 on 2023-01-16 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_bot', '0009_reminders_botusers_consent_datetime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotRatings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=1, verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_bot.botusers', verbose_name='Пользователь бота')),
            ],
            options={
                'verbose_name': 'Оценки бота-регистратора',
                'verbose_name_plural': 'Оценка бота-регистратора',
                'db_table': 'Оценка бота-регистратора',
                'ordering': ['-id'],
            },
        ),
        migrations.DeleteModel(
            name='Reminders',
        ),
    ]
