# Generated by Django 4.1.4 on 2023-01-16 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_bot', '0010_botratings_delete_reminders'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='botratings',
            table='Оценки бота-регистратора',
        ),
    ]
