# Generated by Django 4.1.4 on 2023-01-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_bot', '0011_alter_botratings_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='botratings',
            name='comment',
            field=models.CharField(blank=True, max_length=4096, null=True, verbose_name='Комментарий'),
        ),
    ]
