# Generated by Django 4.1.4 on 2023-01-23 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration_bot', '0012_botratings_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('p', 'оплата'), ('s', 'подпись')], default='p', max_length=1, verbose_name='Тип напоминания')),
                ('proc_id', models.CharField(max_length=10, verbose_name='ID процесса напоминания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration_bot.botusers', verbose_name='Пользователь')),
            ],
        ),
    ]
