# Generated by Django 4.1.4 on 2023-01-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration_bot', '0013_reminders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reminders',
            options={'ordering': ['-id'], 'verbose_name': 'Напоминания бота-регистратора', 'verbose_name_plural': 'Напоминание бота-регистратора'},
        ),
        migrations.AlterModelTable(
            name='reminders',
            table='Напоминания бота-регистратора',
        ),
    ]
