# Generated by Django 4.1.4 on 2023-01-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_bot', '0015_alter_companydata_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='inn',
            field=models.CharField(max_length=14, verbose_name='ИНН'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='ogrn',
            field=models.CharField(max_length=14, verbose_name='ОГРН'),
        ),
    ]
