# Generated by Django 4.1.4 on 2023-01-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_bot', '0016_alter_companydata_inn_alter_companydata_ogrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminders',
            name='proc_id',
            field=models.CharField(max_length=150, verbose_name='ID процесса напоминания'),
        ),
    ]
