# Generated by Django 4.1.4 on 2023-02-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration_bot', '0018_alter_companydata_inn_alter_companydata_ogrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botusers',
            name='tlg_id',
            field=models.CharField(max_length=30, verbose_name='Telegram ID'),
        ),
    ]
