# Generated by Django 4.1.4 on 2023-03-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vpn_bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VpnBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=230, verbose_name='Ключ')),
                ('value', models.TextField(max_length=500, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'настройка VPN_BOT',
                'verbose_name_plural': 'настройки VPN_BOT',
                'ordering': ['-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='tlguser',
            options={'ordering': ['-id'], 'verbose_name': 'пользователь TG', 'verbose_name_plural': 'пользователи TG'},
        ),
    ]
